sudo: false
language: node_js
node_js:
  - node
before_script:
  - npm install -g gulp
install:
  - npm i npminstall && npminstall
  - gulp
script:
  - npm run ci
after_script:
  - npminstall codecov && codecov
